# Site Settings
title: E. Husić
#url: 'http://webjeda.com'
baseurl: '/page' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Edin Husić 
#tagline: Full Stack Developer
pic: pic1.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Currently I am a PhD student at London School of Economics working under supervision of 
<a href="http://personal.lse.ac.uk/veghl/" target="_defualt">László A. Végh</a> and 
<a href="http://personal.lse.ac.uk/sorkin/" target="_defualt">Gregory Sorkin</a>. 
You can find out more about me in 
<a href="https://github.com/zhero9/page/blob/master/cv.pdf?raw=true" target="_defualt"><b>CV</b></a> (February 2018).
<span class='quora-content-embed' data-name='What-is-a-greedy-algorithm/answer/Edin-Husić'>Read <a class='quora-content-link' data-width='560' data-height='260' href='https://www.quora.com/What-is-a-greedy-algorithm/answer/Edin-Husić' data-type='answer' data-id='74354029' data-key='d00b85bce1c13c0d0d42d5e56514945b' load-full-answer='False' data-embed='cfzxeww'><a href='https://www.quora.com/Edin-Husić'>Edin Husić</a>&#039;s <a href='/What-is-a-greedy-algorithm#ans74354029'>answer</a> to <a href='/What-is-a-greedy-algorithm' ref='canonical'><span class="rendered_qtext">What is a greedy algorithm?</span></a></a> on <a href='https://www.quora.com'>Quora</a><script type="text/javascript" src="https://www.quora.com/widgets/content"></script></span>'

#sidebar links if you enter institution, you have to enter instutition site in instSite!
institution: 'Department of Mathematics, London School of Economics and Political Science'
instSite: 'http://www.lse.ac.uk/Mathematics'
address: 'Houghton Street, London, WC2A 2AE, United Kingdom'
email: e.husic at lse.ac.uk
github: zhero9
quora: 'profile/Edin-Husić'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker#
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
